#!/usr/bin/env bash
# This script reads /etc/passwd and prints a story about each user

while IFS=: read -r username password userid groupid userinfo home shell; do
  echo "The user $username is part of $groupid gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo" | sed 's/[[:space:]]*$//'
done < /etc/passwd
